export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_REQUEST = 'REQUEST_REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REQUEST_REGISTER_USER'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'
